### ISSUE TITLE
Bug: Changing the default Git username

### ISSUE THREAD

**Issue by serhii-korniichuk** [all-you-need-is-laugh/git-setup-helper#2]
### Version

1.0.0 (Edge)

### What did you expect to happen?

The default username should have changed.

### What actually happened?

<details>
<summary>Output</summary>

```
In step 5, when you try to change the automatically generated name, it gives an error.
```
</details>

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

👀 Screenshot where you can see all the steps, including the error:

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/60781734/163710442-30983045-88ea-4595-a47f-e27582ffb82c.png">

**Comment by all-you-need-is-laugh** [comment]
@SerhiiKorniichuk, please, try version from [fix branch](https://github.com/all-you-need-is-laugh/git-setup-helper/tree/2-bug-changing-the-default-git-username)

**Comment by serhii-korniichuk** [comment]
@all-you-need-is-laugh I got another error related to access. But the ssh key was added as before.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/60781734/163715843-9b9e2579-72ae-4e0a-9c72-300fd8064662.png">

**Comment by all-you-need-is-laugh** [comment]
@SerhiiKorniichuk you specified `-p ./Workspace/Projects`, which must point to final folder, i.e. `-p ./Workspace/Projects/expense-app`. Try proper value

**Comment by serhii-korniichuk** [comment]
@all-you-need-is-laugh After `ggg -e skorniychyk@gmail.com -p ./Workspace/Projects/expense-app -r git@github.com:SerhiiKorniichuk/expense-app.git -d`, got this:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/60781734/163733052-f3dd61a6-798e-4873-aefe-cdea3d5ca82c.png">

**Comment by all-you-need-is-laugh** [comment]
@SerhiiKorniichuk What output do you get for the following command? (with generated and added to github.com SSH-key)
```shell
$ ssh -T github.com-skorniychyk__gmail.com
```

**Comment by serhii-korniichuk** [comment]
@all-you-need-is-laugh 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/60781734/163814191-78861a28-771d-45a0-ba69-3f697077d412.png">

**Comment by serhii-korniichuk** [comment]
@all-you-need-is-laugh I noticed when `ggg` makes a new setting in the config file, I see that `IdentityFile undefined`. Shouldn't there be a path to the file?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60781734/163814473-edf78cd0-4095-428a-9d84-9a268982462a.png">

**Comment by all-you-need-is-laugh** [comment]
@SerhiiKorniichuk, please, check now (from branch) - should be fixed

**Comment by serhii-korniichuk** [comment]
@all-you-need-is-laugh  Great, everything works. Thanks for your help! ❤️
