### ISSUE TITLE
Feature Request: Adding custom port

### ISSUE THREAD

**Issue by VOV44ER** [all-you-need-is-laugh/git-setup-helper#4]
### Version

1.0.1

### What problem do you want to solve?

Hi, today I ran into a case when I needed to add a custom port, it's not a problem to add it later to the config file manually.

### What do you think is the correct solution?

It could be a great option to add it straightaway, like other options, like: -p 22022

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by all-you-need-is-laugh** [comment]
@VOV44ER, please, try with version from [feature branch](https://github.com/all-you-need-is-laugh/git-setup-helper/blob/4-feature-request-adding-custom-port/ggg)

**Comment by all-you-need-is-laugh** [comment]
@VOV44ER did you have any chance to try version from [feature branch](https://github.com/all-you-need-is-laugh/git-setup-helper/blob/4-feature-request-adding-custom-port/ggg) ?

**Comment by VOV44ER** [comment]
Hi, i will try as soon as possible
Чт, 12 мая 2022 г. в 14:47, all-you-need-is-laugh ***@***.***

**Comment by VOV44ER** [comment]
Hi, all is worked for me =) Thanks)
